version: '3'

services:
  simplearchitecture:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "34010:80"

  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "34020:80"

  authservice.database:
    image: mongo:latest
    ports:
      - "34021:27017"