version: '3'

services:
  simplearchitecture:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "33000:80"

  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "33001:80"
