version: '3'

services:
  simplearchitecture:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "33000:80"

  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "33001:80"

  authservice.database:
    image: mongo:latest
    ports:
      - "33002:27017"